Repository g-adopt/g-adopt, pull requests merged in 2023-10, with the labels that each got.

#28 Adjust penalty term in weak imposition of velocity boundary conditions.
  demos/2d_cylindrical/expected.pkl
  demos/3d_spherical/expected.pkl
  demos/analytical_comparisons/test_analytical.py
  gadopt/stokes_integrators.py
Labels: enhancement

#27 Testing fixes (unpin pyadjoint, add timing)
  .github/workflows/test.yml
  demos/2d_compressible_ALA/Makefile
  demos/2d_compressible_TALA/Makefile
  demos/2d_cylindrical/Makefile
  demos/3d_cartesian/Makefile
  demos/3d_spherical/Makefile
  demos/Drucker-Prager_rheology/Makefile
  demos/adjoint/Makefile
  demos/analytical_comparisons/Makefile
  demos/base_case/Makefile
  demos/optimisation_checkpointing/Makefile
  demos/viscoplastic_case/Makefile
Labels: testing, maintenance

#32 Enforce implementation of abstract methods
  gadopt/approximations.py
Labels: bug

#34 Cancel in-progress CI runs on PR update
  .github/workflows/test.yml
Labels: testing

#37 Permit layer averaging in 3D (default to layers of extruded mesh)
  demos/3d_spherical/3d_spherical.py
  demos/3d_spherical/expected.pkl
  demos/generate_expected.py
  demos/test_all.py
  gadopt/utility.py
Labels: enhancement

#26 Add spherical analytical with long test framework
  .github/workflows/lint.yml
  .github/workflows/longtest.yml
  .github/workflows/test.yml
  Makefile
  demos/Makefile
  demos/adjoint/cases.py
  demos/adjoint/taylor_test.py
  demos/adjoint/test_adjoint.py
  demos/adjoint_2d_cylindrical/cases.py
  demos/adjoint_2d_cylindrical/taylor_test.py
  demos/adjoint_2d_cylindrical/test_cylindrical_adjoint.py
  demos/analytical_comparisons/Makefile
  demos/analytical_comparisons/analytical.py
  demos/analytical_comparisons/run_gadi.sh
  demos/analytical_comparisons/smooth_spherical_freeslip.py
  demos/analytical_comparisons/smooth_spherical_zeroslip.py
  demos/analytical_comparisons/test_analytical.py
  pytest.ini
Labels: testing, enhancement

#38 Create workflow summaries for test status and timings
  .github/workflows/test.yml
Labels: testing

#41 Add parallel scaling to longtest framework
  demos/Makefile
  demos/parallel_scaling/Level_5/get_data.py
  demos/parallel_scaling/Level_5/job.sh
  demos/parallel_scaling/Level_5/stokes_cubed_sphere_7e3_A3.py
  demos/parallel_scaling/Level_5/stokes_cubed_sphere_7e3_A3_TS1.py
  demos/parallel_scaling/Level_6/get_data.py
  demos/parallel_scaling/Level_6/job.sh
  demos/parallel_scaling/Level_6/stokes_cubed_sphere_7e3_A3.py
  demos/parallel_scaling/Level_6/stokes_cubed_sphere_7e3_A3_TS1.py
  demos/parallel_scaling/Level_7/get_data.py
  demos/parallel_scaling/Level_7/job.sh
  demos/parallel_scaling/Level_7/stokes_cubed_sphere_7e3_A3.py
  demos/parallel_scaling/Level_7/stokes_cubed_sphere_7e3_A3_TS1.py
  demos/parallel_scaling/Level_8/get_data.py
  demos/parallel_scaling/Level_8/job.sh
  demos/parallel_scaling/Level_8/stokes_cubed_sphere_7e3_A3.py
  demos/parallel_scaling/Level_8/stokes_cubed_sphere_7e3_A3_TS1.py
  demos/parallel_scaling/Makefile
  demos/parallel_scaling/expected.csv
  demos/parallel_scaling/plot_scaling_diagnostics.py
  demos/parallel_scaling/run_gadi.sh
  demos/parallel_scaling/scaling.py
  demos/parallel_scaling/stokes_cubed_sphere.py
  demos/parallel_scaling/test_scaling.py
Labels: testing
