Repository g-adopt/g-adopt, pull requests merged in 2024-11, with the labels that each got.

#124 Improve TALA DG serial/parallel consistency
  tests/2d_cylindrical_TALA_DG/2d_cylindrical_TALA_DG.py
  tests/2d_cylindrical_TALA_DG/Makefile
  tests/2d_cylindrical_TALA_DG/expected.pkl
Labels: testing, question, answer change

#129 PDE-constrained optimisation
  .github/workflows/test.yml
  demos/.diagram.mermaid
  demos/.pages
  demos/Makefile
  demos/PDE_constrained_optimisation/Makefile
  demos/PDE_constrained_optimisation/PDE_constrained_boundary.py
  demos/PDE_constrained_optimisation/PDE_constrained_field.py
  demos/PDE_constrained_optimisation/test_pde_constrained_optimisation.py
Labels: demo

#139 Plot log(mu) at end of viscoplastic demo
  demos/mantle_convection/viscoplastic_case/viscoplastic_case.py
Labels: demo

#140 Make triggering a documentation rebuild optional
  .github/workflows/render.yml
Labels: maintenance

#147 Serialise startup of render jobs
  demos/Makefile
Labels: maintenance

#148 Run render jobs with namespaced networking
  .github/workflows/render.yml
  .testing/jupytext
  demos/Makefile
Labels: maintenance
