Repository g-adopt/g-adopt, pull requests merged in 2025-05, with the labels that each got.

#213 Update expected test results for PETSc version bump
  demos/mantle_convection/2d_compressible_ALA/Makefile
  demos/mantle_convection/2d_compressible_TALA/Makefile
  tests/free_surface/expected_errors.npz
  tests/multi_material/test_multi_material.py
Labels: answer change

#217 Use correct type for optimisation parameters
  gadopt/inverse.py
Labels: maintenance

#202 Update free surface setup in `StokesSolver` using new `set_equations` and `set_form` methods
  demos/mantle_convection/free_surface/free_surface.py
  gadopt/approximations.py
  gadopt/equations.py
  gadopt/preconditioners.py
  gadopt/stokes_integrators.py
  tests/free_surface/implicit_cylindrical_free_surface.py
  tests/free_surface/implicit_free_surface.py
  tests/free_surface/implicit_top_bottom_free_surface.py
Labels: dev meeting
