Repository g-adopt/g-adopt, pull requests merged in 2025-06, with the labels that each got.

#186 Level-set initialisation API
  demos/multi_material/compositional_buoyancy/compositional_buoyancy.py
  demos/multi_material/thermochemical_buoyancy/thermochemical_buoyancy.py
  gadopt/__init__.py
  gadopt/level_set_tools.py
  gadopt/utility.py
  tests/multi_material/benchmarks/crameri_2012.py
  tests/multi_material/benchmarks/gerya_2003.py
  tests/multi_material/benchmarks/robey_2019.py
  tests/multi_material/benchmarks/schmalholz_2011.py
  tests/multi_material/benchmarks/schmeling_2008.py
  tests/multi_material/benchmarks/tosi_2015.py
  tests/multi_material/benchmarks/trim_2023.py
  tests/multi_material/benchmarks/van_keken_1997_isothermal.py
  tests/multi_material/benchmarks/van_keken_1997_thermochemical.py
  tests/multi_material/initial_signed_distance.py
  tests/multi_material/run_benchmark.py
Labels: dev meeting, ready

#185 Update `LevelSetSolver`
  demos/multi_material/compositional_buoyancy/compositional_buoyancy.py
  demos/multi_material/thermochemical_buoyancy/thermochemical_buoyancy.py
  gadopt/level_set_tools.py
  tests/multi_material/run_benchmark.py
Labels: ready, In Progress

#188 Remove `density_RaB` from level-set API
  demos/multi_material/compositional_buoyancy/compositional_buoyancy.py
  demos/multi_material/thermochemical_buoyancy/thermochemical_buoyancy.py
  gadopt/__init__.py
  gadopt/level_set_tools.py
  gadopt/stokes_integrators.py
  tests/multi_material/benchmarks/crameri_2012.py
  tests/multi_material/benchmarks/gerya_2003.py
  tests/multi_material/benchmarks/robey_2019.py
  tests/multi_material/benchmarks/schmalholz_2011.py
  tests/multi_material/benchmarks/schmeling_2008.py
  tests/multi_material/benchmarks/tosi_2015.py
  tests/multi_material/benchmarks/trim_2023.py
  tests/multi_material/benchmarks/van_keken_1997_isothermal.py
  tests/multi_material/benchmarks/van_keken_1997_thermochemical.py
  tests/multi_material/run_benchmark.py
Labels: ready, In Progress

#244 Trigger github_status rebuild when new memory profiling plots are created
  .github/workflows/memprof_plot.yml
Labels: ready

#251 Pin VTK for pyvista compatibility
  pyproject.toml
Labels: maintenance, external

#256 Fix `get_boundary_ids` and `test_boundary_detection`
  gadopt/utility.py
  tests/unit/test_boundary_detection.py
Labels: bug
