Repository g-adopt/g-adopt, pull requests merged in 2025-07, with the labels that each got.

#250 Final minor improvements to `level_set_tools.py`
  gadopt/level_set_tools.py
Labels: maintenance, ready

#254 Code improvements/fixes identified whilst testing 3-D level set
  gadopt/equations.py
  gadopt/level_set_tools.py
  gadopt/stokes_integrators.py
Labels: bug, enhancement, ready

#258 Allow material entrainment calculation on "non-Cartesian" meshes
  gadopt/level_set_tools.py
Labels: enhancement, ready

#257 Fix warnings produced through unit tests
  gadopt/limiter.py
  tests/unit/test_continuity.py
  tests/unit/test_extrusion_tools.py
  tests/unit/test_limiters.py
Labels: maintenance, ready

#198 Demo for dynamic topography
  demos/.diagram.mermaid
  demos/.pages
  demos/Makefile
  demos/makefile.cases.inc
  demos/mantle_convection/Makefile
  demos/mantle_convection/dynamic_topography/Makefile
  demos/mantle_convection/dynamic_topography/dynamic_topography.py
  demos/mantle_convection/dynamic_topography/expected.pkl
  demos/test_all.py
Labels: ready
